### ISSUE TITLE
Stuck at Pulling Files, "Cannot create directory, file already exists" even on fresh install

### ISSUE THREAD

**Issue by Beth-Whitney** [pantheon-systems/localdev-issues#103] opened 2021-02-19 16:39 UTC
Even when working from a completely fresh installation of LocaDev the error when copying git clone over to /app

cp: cannot create directory '/app/vendor/mikey179/vfsstream': File exists
Killing...

Please note there appears to have been the same bug reported here by a different user which was closed without resolution:
https://github.com/pantheon-systems/localdev-issues/issues/29

FRom Install log:
	/private/tmp/lando/docker
"disk3" ejected.
/Library/LaunchDaemons/com.docker.vmnetd.plist: Could not modify plist, error: Value 56 already exists at key path Version

other logs attached
[lando-error.log](https://github.com/pantheon-systems/localdev-issues/files/6011517/lando-error.log)

Adding screenshot- the site does download fully, including this vendor file. However I am attaching a screenshot in the event it's a case issue (the vendor directory is not all lowercase) that could be causing this.
![Screen Shot 2021-02-19 at 12 05 14 PM](https://user-images.githubusercontent.com/79326675/108537448-9afa4880-72ab-11eb-9de2-99cf49c92828.png)

**Comment by pirog** [comment] 2021-10-05 19:21
@Beth-Whitney _pretty sure_ this is a dupe of #83 so going to close in favor of the longer lived once

**Closed as completed by pirog** 2021-10-05 19:21 UTC
