### ISSUE TITLE
0.8.0-beta1 - Can't Push Code

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/localdev-issues#47] opened 2020-03-07 01:13 UTC
Working off the latest beta I do not appear to be able to push code. There are no errors in the logs that I can see, but if I open a terminal and look in the directory for the site, the files are changed but not committed. There's nothing in the local commit log, leading me to believe that the failure is on the commit, not the push.

The only relevant line from the localdev log appears to be:

```
{"level":"verbose","message":"/Applications/Docker.app/Contents/Resources/bin/docker,exec,--user,www-data,--workdir,/app,--env,PHP_MEMORY_LIMIT=-1,pld-outlandishjosh_appserver_1,/helpers/push.sh,--auth=-iZFLyK5fUvoqFrxehNH0-6hlKbBKShW-GV8AZ_JR47My,--code=dev,--database=none,--files=none,--message=Committing again finished with code 0","timestamp":"2020-03-07T01:04:17.639Z"}
```

Which is a lando function. I'm not sure where to go for log output for this.

**Comment by dustinleblanc** [comment] 2020-03-09 14:25
Investigating this more, it seems that the issue is related to the user's `git config` not being set. We're discussing ways to fix this upstream

**Comment by dustinleblanc** [comment] 2020-03-09 14:55
Steps to reproduce:

1. Spin up a site with localdev
2. change into the directory of pulled site
3. Run `git config user.name ""` and `git config user.email ""`
4. Run `touch foo.txt` (or make some other code change)
5. Go to the push tab of the cloned app in Localdev and check `Push code`
6. Scroll down and add a commit message
7. Click the push button
8. Ensure devtools are open, and see something like this in the logs:

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'www-data@8b79c72c4267.(none)')
```

You will see no workflow run on Pantheon and no new commit.

This is fixed by running:
```
git config --global user.name "Dustin LeBlanc"
git config --global user.email "dustin.m.leblanc@gmail.com"
```

**Comment by joshkoenig** [comment] 2020-03-09 17:03
I am able to replicate. This might have something to do with the internal Lando environment:

`fatal: unable to auto-detect email address (got 'www-data@e949b2ca22b8.(none)')`

My native MacOS git environment is set up, but this is not carrying over for some reason.

**Comment by dustinleblanc** [comment] 2020-03-09 17:28
Yep, we're planning to attack this at the Lando layer to dynamically set the git config info if it isn't already set.

**Closed as completed** 2020-07-16 13:45 UTC
