### ISSUE TITLE
Database connection info for running site isn't usable

### ISSUE THREAD

**Issue by mlangone** [pantheon-systems/localdev-issues#10] opened 2019-04-17 18:17 UTC
This may be a feature request but with other local devs there is at least a phpmyadmin option.

1. where is the database located on local
2. is it possible to add support for Adminer/Sequel Pro
3. Documentation is lacking on how to get to the database.

**Comment by joshkoenig** [comment] 2019-04-18 22:38
Fair point! Not sure about including a DB gui in the tool (that's a good idea), but it's a no-brainer to make the connection info easily accessible to use with your tool of choice.

**Comment by carl-alberto** [comment] 2019-05-10 14:43
From the looks of the LocalDev dashboard, it displays db connection info but have unknown values https://screencast.com/t/0jxEqrxJUrr

**Comment by joshkoenig** [comment] 2019-05-15 20:49
I'd like to fix this UI so it's at least actionable before the next release:

![image](https://user-images.githubusercontent.com/143186/57808446-3c885980-7718-11e9-8f82-9d355ecc41e3.png)

Once that's done we can look at bundling a tool like phpMyAdmin.

**Comment by pirog** [comment] 2019-05-20 16:30
Looks like this (db connection info surfacing in the GUI) is actually a regression that was noted after the 0.4.0 release
https://github.com/pantheon-systems/localdev/issues/111

Adding this into the current sprint for 0.4.1. 

@mlangone i'd spin up a new ticket/feature request for a DB GUI. Lando already offers a phpmyadmin service so on a technical level this is possible. Personal opinion is that i don't think offering a GUI tool for DB access should be the default out of the box setting for PLD but could be an opt in featue. Definitely interested to hear from more users about what they would prefer.

**Comment by pirog** [comment] 2019-05-21 18:40
Should be fixed in the `0.4.1` release. Guessing you will need to restart relevant apps to see the updated port data.

**Comment by carl-alberto** [comment] 2019-05-21 21:59
Tried to upgrade to 0.4.1 and verified it is now working! https://screencast.com/t/xwrvzyPk

**Comment by joshkoenig** [comment] 2019-06-03 21:00
I'm seeing the info updated in `0.4.1` but I cannot connect via my CLI.

**Comment by pirog** [comment] 2019-06-05 16:04
@joshkoenig alright i did some digging here and i don't think this is actually a PLD issue and might be best surfaced in the documentation as a "gotcha".

```bash
# Doesn't work
mysql -P 32834 -ppantheon -upantheon pantheon
mysql -h localhost -P 32834 -ppantheon -upantheon pantheon

# Works
mysql -h 127.0.0.1 -P 32834 -ppantheon -upantheon pantheon
mysql --protocol tcp -P 32834 -ppantheon -upantheon pantheon
```

I think `mysql` defaults to using the socket for connections and the PLD database is exposed via tcp. e Presumably your `mysql` command is attempting to connect over a local socket to a mysql server you have running on your mac which doesn't have the `pantheon:pantheon@pantheon` database.

**Comment by joshkoenig** [comment] 2019-06-05 16:56
@pirog I probably should have uncovered that myself. 😛  

Should we consider changing the hostname value to `127.0.0.1` to help prevent confusion?

**Comment by pirog** [comment] 2019-06-11 17:55
@joshkoenig beyond more people being used to "localhost" i don't see a ton of downside in that change. 

to me "works the most consistently and reliably" is higher in the hierarchy of needs than "something im used to". 

I'm about to roll a new release and going to make the executive decision to roll in your proposed change without further discussion! ;)

**Comment by joshkoenig** [comment] 2019-06-11 18:12
@pirog I'll take a look at the code and make a suggestion

**Comment by pirog** [comment] 2019-06-11 18:24
@joshkoenig sounds good. just checked out your PR and 👍

**Comment by joshkoenig** [comment] 2019-06-11 18:27
Awesome; thanks!

**Comment by royboy789** [comment] 2019-06-26 03:57
Looking for an update on this. I see the Database info, however `localhost` is relative to the container, right? So loading up SequelPro doesn't help, would be nice to have info relative to the filesystem, not the container, if that makes sense.

**Comment by joshkoenig** [comment] 2019-07-09 22:27
Hey @royboy789 - localhost is not just relevant to the container. The DB is exposed to the host machine/OS to make it easier to connect with your favorite GUI tools. The UI has been updated like so:

![image](https://user-images.githubusercontent.com/143186/60927240-05d54800-a25e-11e9-893d-09a1b77319e4.png)

And this info should work fine for SequelPro or any other MySQL client.

**Comment by joshkoenig** [comment] 2019-07-30 22:48
@royboy789 are you able to confirm that this did or didn't fix the issue?

**Closed** 2019-10-10 13:38 UTC
Labels: bug
